export let jsonData = `{
  "1": {"id": "1", "name": "Arzar Shamaki", "age": 21, "bday": "1.1.2000", "address": "That Street", "phone": "123 456789", "civilstatus": "married", "kids": "none", "hobbies": "walking", "email": "that@mail.com", "occupation": "That job", "prevoccupation": "the other job", "military": "none", "club": "none", "legal": "parking ticket", "political": "right", "notes": "looks goofy"},
  "2": {"id": "2", "name": "Beboon Tawakasaki", "age": 25, "bday": "1.1.2000", "address": "That Street", "phone": "123 456789", "civilstatus": "married", "kids": "none", "hobbies": "walking", "email": "that@mail.com", "occupation": "That job", "prevoccupation": "the other job", "military": "none", "club": "none", "legal": "parking ticket", "political": "right", "notes": "looks goofy"},
  "3": {"id": "3", "name": "Max Bulk", "age": 22, "bday": "1.1.2000", "address": "That Street", "phone": "123 456789", "civilstatus": "married", "kids": "none", "hobbies": "walking", "email": "that@mail.com", "occupation": "That job", "prevoccupation": "the other job", "military": "none", "club": "none", "legal": "parking ticket", "political": "right", "notes": "looks goofy"},
  "4": {"id": "4", "name": "Sherbert Gurtel", "age": 27, "bday": "1.1.2000", "address": "That Street", "phone": "123 456789", "civilstatus": "married", "kids": "none", "hobbies": "walking", "email": "that@mail.com", "occupation": "That job", "prevoccupation": "the other job", "military": "none", "club": "none", "legal": "parking ticket", "political": "right", "notes": "looks goofy"},
  "5": {"id": "5", "name": "John Doe", "age": 25, "bday": "1.1.2000", "address": "That Street", "phone": "123 456789", "civilstatus": "married", "kids": "none", "hobbies": "walking", "email": "that@mail.com", "occupation": "That job", "prevoccupation": "the other job", "military": "none", "club": "none", "legal": "parking ticket", "political": "right", "notes": "looks goofy"}
}`
// not working
// export let jsonData = fetch('http://127.0.0.1:8080/persons', {mode: 'no-cors'})
// .then((response) => response.json());
